---
author: "Marc Gumowski"
categories:
- JavaScript
- R language
d3: yes
layout: dbplot
output: html_document
css: src/styles.css
tags:
- D3
- Chord Diagram
---

```{r setup, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Install packages
list.of.packages <- c("readxl", "RODBC", "magrittr", "plyr", "zoo", "data.table", "extrafont", 
                      "RColorBrewer", "viridis", "dplyr", "sp", "gridSVG",
                      "knitr", "jsonlite")
new.packages     <- list.of.packages[!(list.of.packages %in% installed.packages()[ ,"Package"])]
if(length(new.packages)) {
  install.packages(new.packages)
}

# Load packages
invisible(lapply(list.of.packages, library, character.only = TRUE))
# invisible(extrafont::loadfonts(device="win"))

# Load data
dbplot           <- read_excel("data.xlsx")
  
# Transform in billion USD
dbplot$value     <- dbplot$value / 10^9
# Matrix format
dbplot           <- dcast(dbplot, exporterRegion ~ importerRegion, value.var = "value")
# Remove name column
dbplot           <- as.matrix(dbplot[ ,-1])
rownames(dbplot) <- colnames(dbplot)

# Names file
dbplotName       <- data.frame(name = colnames(dbplot),
                              shortName = c(colnames(dbplot)[1:2],
                                            "CIS",
                                            colnames(dbplot)[4:6],
                                            "LATCAR"))

# Imports (need to invert the matrix to have the imports, otherwise it is export)
dbplot           <- t(dbplot)

```

<head><title> Chord Diagram </title></head>
<body>
<center><h1>Trade Flow Chart</h1></center>
<div id="chordDiagramInteractive" style="text-align:center; width:100%;"></div>
```{r echo = FALSE, results = 'asis'}
# Data, d3, Chart
cat(
  paste(
    '<script>
    var dbplot = ', toJSON(dbplot), ';
    var dbplotName = ', toJSON(dbplotName), ';
  </script>'
  , sep=""),
'<script src="src/d3v4/d3.min.js"></script>
<script src="src/chordDiagramInteractive.js"></script>
# ')
```
<p> The outer radius of each region represents the amount of imports. The ribbons between the regions represent the trade exchanges, they are colored in the color of the region that imports the most. </p>
</body></html>
